name: HardcoreGames
version: 1.0
main: HG.Main
author: tryingforglory
commands:
  admin:
  arena:
  chat:
  cleardrops:
  dano:
  desistir:
  feast:
  help:
  ip:
  ir:
  killmobs:
  kit:
  pvp:
  random:
  score:
  setkit:
  skit:
  spawn:
  start:
  teleport:
  tempo:
  togglekits:
  tpall:
  tphere:
  who: